services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "exchange"]
      interval: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        # 1) прогоняем миграции
        alembic upgrade head &&
        # 2) запускаем FastAPI
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  pgdata: