services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: exchange
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app               # монтируем код внутрь контейнера
    ports:
      - "8000:8000"           # выдаём наружу порт 8000
    environment:
      # строка подключения к Postgres из контейнера
      DATABASE_URL: postgresql+asyncpg://user:pass123@db:5432/exchange
    depends_on:
      - db

volumes:
  pgdata: