"""Add Order, Transaction, Balance tables

Revision ID: ed83bb048cae
Revises: f8dbfcb34f1d
Create Date: 2025-06-12 18:53:34.097539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed83bb048cae'
down_revision: Union[str, None] = 'f8dbfcb34f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # All tables already exist, skip creation to avoid duplicates
    # op.create_table('instruments', ...)
    # op.create_table('users', ...)
    # op.create_table('balances', ...)
    # op.create_table('orders', ...)
    # op.create_table('transactions', ...)
    # ### no upgrade operations ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # All tables were pre-existing; nothing to drop
    # ### no downgrade operations ###
